### ISSUE TITLE
returned non-zero exit status 127.

### ISSUE THREAD

**Issue by pedrobart** [mthf0/Layla#1]
bin/sh: 1: httprobe: not found
Traceback (most recent call last):
  File "/home/bart/Tools/IP-Scan/layla/layla.py", line 83, in <module>
    get_host   = subprocess.check_output(("echo %s | httprobe -prefer-https" % URL_TARGET), shell=True, text=True)
  File "/usr/lib/python3.9/subprocess.py", line 424, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "/usr/lib/python3.9/subprocess.py", line 528, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command 'echo https://VULNsite.com | httprobe -prefer-https' returned non-zero exit status 127.

**Comment by soheilbandei** [comment]
install https://github.com/tomnomnom/httprobe

**Comment by pedrobart** [comment]
> install https://github.com/tomnomnom/httprobe

thank you.

**Comment by pedrobart** [comment]
> install https://github.com/tomnomnom/httprobe

@soheilbandei thank you.
